version: '3.4'

services:
  order-service.webapi:
    image: orderservicewebapi:dev
    container_name: "Order-Service.WebApi_1"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Order-Service.WebApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\malik\source\repos\MicroservicesWithRabittMQ\Order-Service-webApi:/app:rw
      - C:\Users\malik\source\repos\MicroservicesWithRabittMQ:/src:rw
      - C:\Users\malik\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\malik\.nuget\packages:/.nuget/packages:ro
      - C:\Users\malik\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\malik\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\malik\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\malik\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/Order-Service.WebApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
  user-service.webapi:
    image: userservicewebapi:dev
    container_name: "User-Service.WebApi"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "User-Service.WebApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\malik\source\repos\MicroservicesWithRabittMQ\User-Service-webApi:/app:rw
      - C:\Users\malik\source\repos\MicroservicesWithRabittMQ:/src:rw
      - C:\Users\malik\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\malik\.nuget\packages:/.nuget/packages:ro
      - C:\Users\malik\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\malik\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\malik\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\malik\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/User-Service.WebApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
